# Generated by Django 3.0.2 on 2020-01-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='term',
            table='term',
        ),
    ]
