# Generated by Django 3.0.2 on 2020-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200129_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_df',
            field=models.IntegerField(verbose_name='term_df'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_id',
            field=models.IntegerField(verbose_name='term_id'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_stem',
            field=models.CharField(max_length=100, verbose_name='term_stem'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_term',
            field=models.CharField(max_length=100, verbose_name='term_term'),
        ),
    ]
