# Generated by Django 3.0.2 on 2020-01-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200129_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTerm',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('term_id', models.IntegerField()),
                ('tf', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_term',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_version', models.IntegerField()),
                ('doc_keyword', models.CharField(max_length=100)),
                ('doc_text', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Termsim',
            fields=[
                ('term1_id', models.IntegerField(primary_key=True, serialize=False)),
                ('term2_id', models.IntegerField()),
                ('similarity', models.FloatField()),
            ],
            options={
                'db_table': 'termsim',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'managed': False},
        ),
    ]
