# Generated by Django 3.0.2 on 2020-01-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_djangomigrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
