# Generated by Django 3.2 on 2022-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_djangomigrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('ent_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField(blank=True, null=True)),
                ('ent_type', models.TextField()),
                ('ent_name', models.TextField()),
            ],
            options={
                'db_table': 'entity',
                'managed': False,
            },
        ),
    ]
